### ISSUE TITLE
Add AMP compatibility for the social profiles module

### ISSUE THREAD

**Issue by appscreo** [appscreo/easy-social-share-buttons3#148]

**Comment by yogeshbeniwal** [comment]
@appscreo Social share icons on AMP has couple of issues:

- Double icons shown
- Icons colors not matching with non-amp page

![Screen Shot](https://user-images.githubusercontent.com/7325107/141247784-68e1c92c-0685-4c02-ac2b-9019a23b1ce5.png)

**Comment by appscreo** [comment]
@yogeshbeniwal You look having a problem with the share buttons, not the profiles. For support, you can refer to our support system https://support.creoworx.com
