### ISSUE TITLE
Add support for News Tagging (Share Buttons)

### ISSUE THREAD

**Issue by appscreo** [appscreo/easy-social-share-buttons3#247]
https://newsinitiative.withgoogle.com/training/datatools/ntg?platform=gtag&content=user-engagement__social-sharing

**Comment by yogeshbeniwal** [comment]
@appscreo Does it get triggered on amp posts also?

**Comment by appscreo** [comment]
@yogeshbeniwal No, it won't work. AMP is very limited and you can use those functions (javascript code for tracking). That is actually one of the reasons why most of the users don't use AMP (it is also affecting target ads).
