### ISSUE TITLE
Add WYKOP.pl to supported networks services (polish reddit alternative - much more popular than reddit in Poland)

### ISSUE THREAD

**Issue by createque** [appscreo/easy-social-share-buttons3#35]
WYKOP.pl - polish Reddit alternative is one of the most visited website in Poland.
Next to Facebook, Twitter, Instagram, Google and LinkedIn, WYKOP share button **would be one of the most usefull function in ESSB in Poland**

**Comment by createque** [comment]
WYKOP sharing alredy existing in some other social sharing plugins.
I think existing WYKOP sharing in ESSB is essential.

**Comment by createque** [comment]
WYKOP API documentation:
https://www.wykop.pl/dla-programistow/api/

**Comment by appscreo** [comment]
Thanks for the suggestion. In the plugin, we are using only static API share commands. I think that command here -> https://www.wykop.pl/dla-programistow/wykopywarka/ is more suitable for sharing: `http://www.wykop.pl/dodaj/link/?url=http://adresstrony.pl&title=TUTAJ_TYTUL&desc=TUTAJ_OPIS`

Moved to be added in the extended networks list free add-on.

**Comment by appscreo** [comment]
The integration is ready. The network is built as a separate free add-on. The add-on will be included in the full package of version 7.2. And it will be available for download on https://socialsharingplugin.com

**Comment by createque** [comment]
WOOW! Thank you guys! You`re awsome!

**Comment by appscreo** [comment]
@createque It's available for download at https://socialsharingplugin.com/addons/. Require version 7.0 or newer

**Comment by createque** [comment]
Works like a charm! Thank you!!!
